Updated scripts

diff --git a/17_LXC/01_NetworkIsolatedLXC/lib/functions/logger b/17_LXC/01_NetworkIsolatedLXC/lib/functions/logger
--- a/17_LXC/01_NetworkIsolatedLXC/lib/functions/logger
+++ b/17_LXC/01_NetworkIsolatedLXC/lib/functions/logger
@@ -4,11 +4,11 @@ _FONT_COLOR_GREEN_="\e[32m"
 _FONT_COLOR_YELLOW_="\e[33m"
 
 logger.info() {
-    echo -e "$(date "+%Y-%m-%d %H:%M:%S") - [${__FONT_COLOR_GREEN}INFO${__FONT_COLOR_RESET}] $@"
+    echo -e "$(date "+%Y-%m-%d %H:%M:%S") - [${_FONT_COLOR_GREEN_}INFO${_FONT_COLOR_RESET_}] $@"
 }
 logger.error() {
-    echo -e "$(date "+%Y-%m-%d %H:%M:%S") - [${__FONT_COLOR_RED}ERROR${__FONT_COLOR_RESET}] $@" >&2
+    echo -e "$(date "+%Y-%m-%d %H:%M:%S") - [${_FONT_COLOR_RED_}ERROR${_FONT_COLOR_RESET_}] $@" >&2
 }
 logger.warning() {
-    echo -e "$(date "+%Y-%m-%d %H:%M:%S") - [${__FONT_COLOR_YELLOW}WARNING${__FONT_COLOR_RESET}] $@" >&2
+    echo -e "$(date "+%Y-%m-%d %H:%M:%S") - [${_FONT_COLOR_YELLOW_}WARNING${_FONT_COLOR_RESET_}] $@" >&2
 }
